# Generated by Django 4.1.4 on 2023-06-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('idcomuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='envio',
            fields=[
                ('idEnvio', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=200)),
                ('comentario', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('idMarca', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=43)),
                ('old', models.IntegerField()),
                ('new', models.IntegerField()),
                ('descripcion', models.CharField(max_length=800)),
                ('esContenido', models.CharField(max_length=10)),
                ('esTipoProducto', models.CharField(max_length=20)),
                ('esOrigen', models.CharField(max_length=30)),
                ('esGarantia', models.CharField(max_length=20)),
                ('despacho', models.BooleanField()),
                ('retiro', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='provedor',
            fields=[
                ('idProvedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('idRegion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
    ]
